### ISSUE TITLE
rqt_image_view as a converter?

### ISSUE THREAD

**Issue by Binsoma** [ros-visualization/rqt_image_view#11]
Hi there,

Is there a way to run rqt_image_view as a converter? meaning, simultaneously running and publishing jpeg/png to a topic?

thx

**Comment by dirk-thomas** [comment]
No, the plugin only renders the incoming images and allows to manually export the current frame on button press.

**Comment by dirk-thomas** [comment]
Assuming my comment answered your question I will close this ticket for now. Please feel free to continue commenting.
