### ISSUE TITLE
Error when switching between topics

### ISSUE THREAD

**Issue by mvieth** [ros-visualization/rqt_image_view#26]
When switching between image topics (in my case especially when switching from a topic with rgb images to a topic with depth images) sometimes a segmentation fault occurs. I think [this is the problematic line](https://github.com/ros-visualization/rqt_image_view/blob/fe076acd265a05c11c04f9d04392fda951878f54/src/rqt_image_view/image_view.cpp#L598) and the error occurs when something goes out of scope [here](https://github.com/ros-visualization/rqt_image_view/blob/fe076acd265a05c11c04f9d04392fda951878f54/src/rqt_image_view/image_view.cpp#L609). Maybe a destructor is called on something that should not be destructed?

**Comment by dirk-thomas** [comment]
Please consider to provide a pull request to address the problem.

**Comment by mvieth** [comment]
I am not sure what the problem is. After further testing, I get a variety of errors, e.g:
`OpenCV Error: Assertion failed (tlsSlotsSize > slotIdx) in getData, file /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/core/src/system.cpp, line 1425
terminate called after throwing an instance of 'cv::Exception'
terminate called recursively
  what():  /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/core/src/system.cpp:1425: error: (-215) tlsSlotsSize > slotIdx in function getData`
or
`Error in python: corrupted double-linked list`
or
`Error in python: free(): invalid pointer`
My best guess at the moment is some kind of race condition between threads and the callback function being called too frequently.

**Comment by dirk-thomas** [comment]
A mutex around the usage might resolve the race then.

**Comment by mvieth** [comment]
I have tried the following:
- Remove the global variable `conversion_mat_`, instead make it local in the `callbackImage` function
- Add a parameter `cv::Mat &image` to the functions `invertPixels` and `overlayGrid`, on which they operate

This works perfectly for me (no more errors), and the callback function should basically be reentrant then, so in my opinion this is a good solution. Unless `conversion_mat_`, `invertPixels`, or `overlayGrid` is used somewhere else that I did not notice.
So if you @dirk-thomas also think this is good, I can provide a pull request.
As a side note: the overlay-grid feature only works if the `toCvShare` function in the `try` part succeeds, for me that is only for RGB-images, not depth images. Is this intended? If not, I could make a second pull request for that.

**Comment by dirk-thomas** [comment]
> I can provide a pull request.

Please go ahead and do so. One thing to double check is that when making the variable local it doesn't result in repeated memory allocation / reduced performance.

> I could make a second pull request for that.

Sounds good too.
