### ISSUE TITLE
missing file librqt_image_view.so

### ISSUE THREAD

**Issue by gabrielwaibel** [ros-visualization/rqt_image_view#35]
Hi

if I want to start `rqt_image_view` via `rosrun rqt_image_view rqt_image_view` or just `rqt_image_view` then I get the following error:

    [ERROR] [1592863606.174353422]: Failed to load nodelet [rqt_image_view/ImageView_0] of type [rqt_image_view/ImageView]: Failed to load library /opt/ros/melodic/lib//librqt_image_view.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libopencv_core.so.3.2: cannot open shared object file: No such file or directory)
    RosPluginlibPluginProvider::load_explicit_type(rqt_image_view/ImageView) failed creating instance
    PluginManager._load_plugin() could not load plugin "rqt_image_view/ImageView": RosPluginlibPluginProvider.load() could not load plugin "rqt_image_view/ImageView"
    terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
    pure virtual method called
    terminate called recursively
    Aborted (core dumped)

the same happens for `rosrun image_view image_view`

    [ INFO] [1592863868.679032143]: Initializing nodelet with 12 worker threads.
    [ERROR] [1592863868.692291840]: Failed to load nodelet [/image_view] of type [image_view/image] even after refreshing the cache: Failed to load library /opt/ros/melodic/lib//libimage_view.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libopencv_core.so.3.2: cannot open shared object file: No such file or directory)
    [ERROR] [1592863868.692331964]: The error before refreshing the cache was: Failed to load library /opt/ros/melodic/lib//libimage_view.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libopencv_core.so.3.2: cannot open shared object file: No such file or directory)

The problem is that this file `/libimage_view.so` does not exist. The ros installation works fine for all other things (rviz, rqt_plot, ...). The only problem is the image data.

I also tried to this:

    sudo apt-get install ros-melodic-rqt-image-view
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    ros-melodic-rqt-image-view is already the newest version (0.4.14-1bionic.20200530.125139).
    ros-melodic-rqt-image-view set to manually installed.
    0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.

    sudo apt-get install ros-melodic-image-view
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    ros-melodic-image-view is already the newest version (1.15.0-1bionic.20200530.133102).
    ros-melodic-image-view set to manually installed.
    0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.

Does someone have a solution to this problem?

Thanks

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.

**Comment by gabrielwaibel** [comment]
https://answers.ros.org/question/355571/missing-file-librqt_image_viewso/
