### ISSUE TITLE
failed to load rqt_image_view plugin

### ISSUE THREAD

**Issue by christianrauch** [ros-visualization/rqt_image_view#38]
Package:
`ros-foxy-rqt-image-view` version `1.0.4-1focal.20200722.054203`

Running:
`ros2 run rqt_image_view rqt_image_view`

Results in:
``
RosPluginlibPluginProvider::load_explicit_type(rqt_image_view/ImageView) could not load library (Failed to load library /opt/ros/foxy/lib/rqt_image_view/librqt_image_view.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library LoadLibrary error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: Kein Speicher im statischen TLS-Block verfügbar, at /tmp/binarydeb/ros-foxy-rcutils-1.0.1/src/shared_library.c:68)
PluginManager._load_plugin() could not load plugin "rqt_image_view/ImageView": RosPluginlibPluginProvider.load() could not load plugin "rqt_image_view/ImageView"
``

**Comment by jakebonney10** [comment]
This appears to be the same as https://github.com/ros-visualization/rqt_image_view/issues/37

**Comment by dirk-thomas** [comment]
Also asked here: https://answers.ros.org/question/358542/rqt-image-view-cannot-run-in-foxy/

**Comment by dirk-thomas** [comment]
Thanks for the report. Please try the proposed ~fix~ hack from ros-visualization/qt_gui_core#233 and comment here if it resolves the problem for you.

**Comment by christianrauch** [comment]
I believe that the issue was fixed upstream with a new release of `libmysqlclient21`? At least now, even without your PR, I am not getting this error anymore.

Also, as per the comment 8 in upstream bug report https://bugs.launchpad.net/ubuntu/+source/opencv/+bug/1890170, I am getting `BIND_NOW` for `readelf --dynamic /usr/lib/x86_64-linux-gnu/libmysqlclient.so.21.1.21 | grep BIND`.

**Comment by dirk-thomas** [comment]
> This has been fixed upstream by the release of `mysql-8.0_8.0.21-0ubuntu0.20.04.4`:

I don't see how a change in `mysql` can affect this plugin. Afaik it is not part of any of the transitive dependencies.

**Comment by christianrauch** [comment]
> I don't see how a change in `mysql` can affect this plugin. Afaik it is not part of any of the transitive dependencies.

I am also not sure how they are related, but the upstream issue (https://bugs.launchpad.net/ubuntu/+source/opencv/+bug/1890170) that your PR linked to mentions this and the original issue reported here vanished after the `mysql` library got updated (https://bugs.launchpad.net/ubuntu/+source/mysql-8.0/+bug/1889851, comment 13).

For sure, I am not facing the originally reported issue any more and I do not require the proposed PR https://github.com/ros-visualization/qt_gui_core/pull/233.

**Comment by nhjydywd** [comment]
I think the issue does have some relations with `mysql`. 
I met the same problem, and I solved the problem with:
`sudo apt purge mysql-*`
`sudo apt purge ros-noetic-*`
`sudo apt install ros-noetic-desktop-full`
Now my `rqt_image_view` just worked again.
