### ISSUE TITLE
[ros2] missing color_scheme_combo_box

### ISSUE THREAD

**Issue by wodtko** [ros-visualization/rqt_image_view#65]
with PR https://github.com/ros-visualization/rqt_image_view/pull/64 the state of `ui_.color_scheme_combo_box` is saved.\
Unfortunately, the respective entry in the UI file is missing...
in `src/rqt_image_view/image_view.ui` the respective item must be added.

I'm currently testing the fix on my machine, PR follows asap.

**Comment by jacobperron** [comment]
Resolved in #66
