### ISSUE TITLE
[BUG] humble-devel branch

### ISSUE THREAD

**Issue by wodtko** [ros-visualization/rqt_image_view#76]
There is a branch named humble-devel, however, it is obviously a ros1 branch.

I would assume that the humble-devel would branch from rolling-devel at one point, instead, it is almost at master which is also ros1, if I see things correctly.

Please reset humble-devel to any working rolling-devel.

**Comment by rodericktaylor** [comment]
I also spotted this issue. @mabelzhang is listed as the maintainer in the rolling-devel branch. I only mention to attract attention.

**Comment by clalancette** [comment]
I just deleted the branch, since it isn't used anywhere.
